In [10]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge



In [5]:
source_dataset = load_diabetes()
X = source_dataset['data']
y = source_dataset['target']

## Linear regression sklearn

In [6]:
linear_model = LinearRegression()
linear_model.fit(X,y)

LinearRegression()

In [7]:
linear_model.coef_

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [13]:
linear_model.intercept_

152.13348416289597

## Linear regression from stratch


$$ \hat\beta = (X^TX)^{-1}X^Ty$$

In [9]:
beta = np.linalg.inv(X.T@X)@X.T@y
beta

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [16]:
beta_0 = np.mean(y-X@beta)
beta_0

152.13348416289597

In [54]:
###  another approach
X_= np.append( np.ones((len(X),1)),X,axis=1)
beta_=np.linalg.inv(X_.T@X_)@X_.T@y
beta_


array([ 152.13348416,  -10.0098663 , -239.81564367,  519.84592005,
        324.3846455 , -792.17563855,  476.73902101,  101.04326794,
        177.06323767,  751.27369956,   67.62669218])

## Linear regression Ridge sklearn

In [57]:
linear_ridge = Ridge()
linear_ridge.fit(X,y)
linear_ridge.coef_

array([  29.46611189,  -83.15427636,  306.35268015,  201.62773437,
          5.90961437,  -29.51549508, -152.04028006,  117.3117316 ,
        262.94429001,  111.87895644])

In [52]:
linear_ridge.intercept_

152.133484162896

## Linear regression Ridge from stratch

$$ \hat\beta= (X^{T}X + \lambda I)^{-1}X^Ty $$

In [56]:
penalty=np.identity(X_.shape[1])
penalty[0,0]=0
c=1
beta_=np.linalg.inv(X_.T@X_+penalty*c)@X_.T@y
beta_

array([ 152.13348416,   29.46611189,  -83.15427636,  306.35268015,
        201.62773437,    5.90961437,  -29.51549508, -152.04028006,
        117.3117316 ,  262.94429001,  111.87895644])